name: "run-aqa against a local customized JDK"
on: # rebuild any PRs and main branch changes
   push:

jobs:
   build:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v1
     - run: 'wget -P buildJDK https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.6%2B10/OpenJDK11U-jdk_x64_linux_hotspot_11.0.6_10.tar.gz'
     - uses: AdoptOpenJDK/install-jdk@v1
       with:
         version: '11'
         architecture: x64
         source: './buildJDK/OpenJDK11U-jdk_x64_linux_hotspot_11.0.6_10.tar.gz'
         targets: 'JDK_11'
         archiveExtension: '.tar'
     - name: AQA
       uses: adoptium/run-aqa@v1
       with:
         version: '11'
         jdksource: 'install-jdk'
         build_list: 'openjdk'
         target: '_jdk_math'